In [1]:
from utils import load_dataset, preprocessing, TSNE_visualization
import torch
from train import *

dataset = load_dataset('texas')
split_dataset_balanced(dataset, {})
graph = preprocessing(dataset)

In [2]:
graph.y

tensor([3, 0, 2, 3, 4, 3, 0, 0, 3, 0, 3, 3, 3, 3, 3, 4, 3, 3, 0, 3, 0, 3, 3, 3,
        3, 1, 3, 3, 0, 2, 3, 3, 4, 3, 4, 4, 2, 3, 3, 3, 0, 4, 0, 3, 3, 3, 2, 2,
        0, 3, 0, 3, 3, 3, 3, 3, 0, 2, 2, 4, 4, 4, 3, 3, 3, 3, 0, 3, 3, 3, 4, 3,
        3, 4, 4, 3, 0, 3, 0, 3, 4, 3, 2, 4, 2, 4, 3, 3, 0, 3, 3, 3, 0, 3, 3, 4,
        3, 3, 3, 4, 0, 0, 4, 3, 3, 0, 4, 3, 2, 3, 3, 0, 3, 0, 0, 3, 3, 4, 3, 3,
        3, 0, 3, 0, 3, 2, 4, 2, 3, 3, 0, 4, 3, 4, 3, 4, 3, 3, 0, 3, 2, 3, 3, 3,
        3, 3, 3, 2, 3, 4, 3, 4, 3, 3, 3, 3, 0, 2, 0, 2, 3, 3, 4, 3, 0, 3, 3, 2,
        0, 3, 3, 4, 3, 2, 0, 3, 0, 4, 3, 3, 4, 3, 3])

In [6]:
model = MLP(in_channels=graph.num_features,
            out_channels=graph.num_class,
            hidden_channels=32,
            num_layers=3,
            dropout=0.5)

device = 'cuda:1'
model.to(device)
model.train()
optimizer = SGD(model.parameters(), lr=0.01, weight_decay=0.001) 
criterion = nn.CrossEntropyLoss()
graph = graph.to(device)
labels = graph.y

best_val_metric = -torch.inf
pred_test = None 

for epoch in range(200):
    optimizer.zero_grad()
    out = model(graph)
    loss = criterion(out[graph.train_index_A], labels[graph.train_index_A])
    
    loss.backward()
    optimizer.step()
    
    metric = cal_accuracy(graph.y[graph.train_index_A], out[graph.train_index_A])
    _, val_metric = eval(model, graph, 'val', 'accuracy')
    print('metric:', metric, 'val_metric: ', val_metric)
    if val_metric > best_val_metric:
        best_epoch = epoch
        best_val_metric = val_metric
        pred_test = torch.softmax(out, dim=1)
pred_test
# metric_record.append(best_val_metric)
# prediction_record.append(pred_test)    
# best_epoch_record.append(best_epoch) 

metric: 0.3333333432674408 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.1111111119389534
metric: 0.0555555559694767 val_metric:  0.11111111193895

tensor([[0.1651, 0.1984, 0.2050, 0.2157, 0.2158],
        [0.1652, 0.1984, 0.2050, 0.2156, 0.2158],
        [0.1651, 0.1985, 0.2050, 0.2156, 0.2159],
        [0.1652, 0.1984, 0.2050, 0.2157, 0.2158],
        [0.1652, 0.1984, 0.2050, 0.2156, 0.2158],
        [0.1651, 0.1984, 0.2049, 0.2157, 0.2158],
        [0.1651, 0.1984, 0.2050, 0.2156, 0.2158],
        [0.1652, 0.1984, 0.2050, 0.2156, 0.2159],
        [0.1652, 0.1984, 0.2050, 0.2156, 0.2158],
        [0.1651, 0.1985, 0.2050, 0.2156, 0.2158],
        [0.1651, 0.1984, 0.2050, 0.2157, 0.2158],
        [0.1652, 0.1984, 0.2050, 0.2156, 0.2158],
        [0.1651, 0.1985, 0.2050, 0.2156, 0.2158],
        [0.1652, 0.1984, 0.2050, 0.2157, 0.2158],
        [0.1651, 0.1984, 0.2050, 0.2157, 0.2158],
        [0.1651, 0.1984, 0.2050, 0.2157, 0.2158],
        [0.1652, 0.1984, 0.2050, 0.2156, 0.2158],
        [0.1652, 0.1984, 0.2049, 0.2156, 0.2158],
        [0.1652, 0.1984, 0.2050, 0.2157, 0.2158],
        [0.1651, 0.1984, 0.2050, 0.2156, 0.2158],


In [5]:
pred_test

tensor([[0.1795, 0.1790, 0.2175, 0.2163, 0.2078],
        [0.1794, 0.1789, 0.2175, 0.2163, 0.2078],
        [0.1795, 0.1789, 0.2174, 0.2163, 0.2078],
        [0.1794, 0.1789, 0.2176, 0.2164, 0.2077],
        [0.1794, 0.1789, 0.2176, 0.2163, 0.2078],
        [0.1794, 0.1789, 0.2175, 0.2164, 0.2078],
        [0.1795, 0.1789, 0.2175, 0.2163, 0.2078],
        [0.1795, 0.1789, 0.2174, 0.2162, 0.2079],
        [0.1794, 0.1789, 0.2176, 0.2163, 0.2078],
        [0.1794, 0.1790, 0.2175, 0.2163, 0.2078],
        [0.1795, 0.1789, 0.2175, 0.2163, 0.2078],
        [0.1793, 0.1790, 0.2175, 0.2163, 0.2078],
        [0.1794, 0.1789, 0.2175, 0.2163, 0.2078],
        [0.1794, 0.1789, 0.2175, 0.2163, 0.2078],
        [0.1794, 0.1789, 0.2175, 0.2163, 0.2078],
        [0.1794, 0.1789, 0.2175, 0.2164, 0.2078],
        [0.1795, 0.1789, 0.2175, 0.2163, 0.2078],
        [0.1795, 0.1789, 0.2174, 0.2163, 0.2079],
        [0.1794, 0.1789, 0.2175, 0.2163, 0.2079],
        [0.1794, 0.1790, 0.2175, 0.2163, 0.2078],
